### ISSUE TITLE
Error in tl_Localize

### ISSUE THREAD

**Issue by alexandreunivap** [Higgins00/TESS-Localize#4]
Hi,
it seems TESS-Localize is great! Thanks! 
I´m testing the TESS_WD_example.ipynb and it shows the following error message. It seems a problem with np.diag. Are you aware of it?
Regards
Alexandre Oliveira

-------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_15748/2065137151.py in <module>
----> 1 high = tl.Localize(targetpixelfile=tpf, frequencies=high_frequency_list, frequnit=u.uHz, principal_components = 'auto')

~/anaconda3/lib/python3.9/site-packages/TESS_Localize/TESS_Localize.py in __init__(self, targetpixelfile, frequencies, frequnit, gaia, magnitude_limit, principal_components, aperture, method, sigma, mask, gaia_catalog, **kwargs)
    781 
    782         if (self.gaiadata is not None):
--> 783             fh.star_list()
    784             self.starfit= fh.stars.reset_index()
    785 

~/anaconda3/lib/python3.9/site-packages/TESS_Localize/TESS_Localize.py in star_list(self)
    738 
    739                     #sample based on rough scale of error model.
--> 740                     avgscale = np.nanmean(np.sqrt(np.diag(self.error_model.covar)))
    741 
    742                     #sample wide enough, and finely enough

<__array_function__ internals> in diag(*args, **kwargs)

~/anaconda3/lib/python3.9/site-packages/numpy/lib/twodim_base.py in diag(v, k)
    296         return diagonal(v, k)
    297     else:
--> 298         raise ValueError("Input must be 1- or 2-d.")
    299 
    300 

ValueError: Input must be 1- or 2-d.

**Comment by keatonb** [comment]
We are aware of this issue and will fix ASAP.  Thanks for reporting.  The previous version, 0.7.2, does not have this bug (pip install tess-localize==0.7.2). That version has a bug in the "autoaperture" function, but that's not used by default.

**Comment by alexandreunivap** [comment]
Ok, thanks again.
